#! /bin/bash

chmod -R 777 /data
docker run -d -v /data/elasticsearch:/var/lib/elasticsearch -v /data/graphite:/src/graphite/storage/whisper -v /data/grafana:/src/grafana/app/dashboards -p 80:80 -p 81:81 -p 82:82 -p 9000:9000 -p 9201:9201 -p 8125:8125/udp iplayer/metrics
