#! /bin/bash

chmod -R 777 /data
docker run -d -v /data/certificates:/etc/nginx/ssl -v /data/elasticsearch:/var/lib/elasticsearch -v /data/graphite:/src/graphite/storage/whisper -v /data/grafana:/src/grafana/app/dashboards -p 443:443 -p 80:80 -p 82:82 -p 9000:9000 -p 9201:9201 -p 8125:8125/udp -p 8126:8126 iplayer/metrics
