#! /bin/bash

docker run --name grafana --link seyren:seyren --link elasticsearch:elasticsearch --link graphite:graphite -d -p 443:443 -v /data/grafana:/data -v /data/certificates:/certificates iplayer/grafana
