#! /bin/bash

docker run --name grafana --link elasticsearch:elasticsearch --link graphite:graphite -d -p 80:80 -p 443:443 -p 9201:9201 -v /data/grafana:/data -v /data/certificates:/certificates iplayer/grafana
